### ISSUE TITLE
Lab 7 - Error after submitting Automatic Evaluation

### ISSUE THREAD

**Issue by usamabinrauf** [MicrosoftLearning/mslearn-ai-studio#25] opened 2024-10-24 16:54 UTC
# Lab: 07
### Description of issue:
I'm facing the error "**We encountered a problem during your evaluation. Please review the raw JSON file or visit the 'Logs' tab for further details.**" upon submitting the automatic evaluation. I have already tried it on two different locations i.e., **East US** & **East US 2**, but the error still persists.

I have attached screenshots for your reference.

### Screenshots:
![Screenshot_18](https://github.com/user-attachments/assets/f82dda3e-b17c-46bb-8ec2-118f6f09bc53)
![Screenshot_19](https://github.com/user-attachments/assets/a2bf2eee-b49f-4a92-be38-97047dc6dbbf)
![Screenshot_20](https://github.com/user-attachments/assets/508b3d2f-db8b-4c5e-9245-f7934df4595b)

**Comment by madiepev** [comment] 2024-10-28 19:01
@usamabinrauf unfortunately we're unable to reproduce the error across multiple subscriptions (tried Sweden Central and West Europe). The ability to launch automatic runtime could a matter of available quota per region in your subscription.

If you're able to, we recommend raising a support ticket through the Azure portal to get assistance with this error.

If you find a workaround, we'd be happy to include it into the instructions to help others troubleshoot similar errors. Closing this issue for now as it's not an issue with the instructions. Feel free to continue the discussion if you think we can help you!

**Closed by madiepev** 2024-10-28 19:01 UTC
